
enum QuerySortOrder {
    ASC
    DESC
}

type Queue {
    id: Int!
    name: String!
    is_active: Boolean
    current_version: Int
    max_attempts: Int
}

type QueueResult {
    queue_id: Int
    was_created: Boolean
    was_dropped: Boolean
}

type Character {
    id: Int!
    name: String!
    age: Int!
}

type Query {
    hello: String
    foo: Int
    faa: [String]!
    characters(search: String): [Character]!
    character(id: Int!): Character
    
    # list all available queues
    queues(
        sortBy: String,
        sortOrder: QuerySortOrder
    ): [Queue]!
}

type Mutation {
    createCharacter(
        name: String!
        age: Int!
    ): Character

    createQueue(
        name: String!
    ): QueueResult

    dropQueue(
        name: String!
    ): QueueResult
}
