
type Character {
    id: Int!
    name: String!
    age: Int!
}

type Query {
    hello: String
    foo: Int
    faa: [String]!
    characters(search: String): [Character]!
    character(id: Int!): Character
}

type Mutation {
    createCharacter(
        name: String!
        age: Int!
    ): Character
}
