
-- SELECT * FROM fetchq_test__init();
-- SELECT * FROM fetchq_test__create_queue();
-- SELECT * FROM fetchq_test__drop_queue();
-- SELECT * FROM fetchq_test__metrics();
-- SELECT * FROM fetchq_test__push_01();
-- SELECT * FROM fetchq_test__push_02();
-- SELECT * FROM fetchq_test__push_03();
-- SELECT * FROM fetchq_test__pick_01();
-- SELECT * FROM fetchq_test__pick_02();
-- SELECT * FROM fetchq_test__pick_03();
-- SELECT * FROM fetchq_test__pick_04();
-- SELECT * FROM fetchq_test__mnt_make_pending_01();
-- SELECT * FROM fetchq_test__mnt_reschedule_orphanse_01();
-- SELECT * FROM fetchq_test__mnt_mark_dead_01();
-- SELECT * FROM fetchq_test__mnt_run_01();
-- SELECT * FROM fetchq_test__mnt_run_all_01();
-- SELECT * FROM fetchq_test__reschedule_01();
-- SELECT * FROM fetchq_test__reschedule_02();
-- SELECT * FROM fetchq_test__log_error_01();
-- SELECT * FROM fetchq_test__log_error_02();
-- SELECT * FROM fetchq_test__reject_01();
-- SELECT * FROM fetchq_test__reject_02();
-- SELECT * FROM fetchq_test__complete_01();
-- SELECT * FROM fetchq_test__complete_02();
SELECT * FROM fetchq_test__kill_01();
SELECT * FROM fetchq_test__kill_02();
